services:
  - type: web
    name: ai-study-tutor
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: GROQ_API_KEY
        sync: false
    disk:
      name: ai-study-tutor-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
